kind: Service
apiVersion: v1
metadata:
  name: springbootcidcpockubernetes-moduleb
spec:
  selector:
    app: springbootcidcpockubernetes-moduleb
    tier: backend
  ports:
    - protocol: TCP
      port: 8090
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootcidcpockubernetes-moduleb
spec:
  selector:
    matchLabels:
      app: springbootcidcpockubernetes-moduleb
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: springbootcidcpockubernetes-moduleb
        tier: backend
    spec:
      containers:
        - name: springbootcidcpockubernetes-moduleb
          image: springbootcidcpockubernetes-moduleb
          imagePullPolicy: Never
          ports:
            - containerPort: 8090         